{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: artifactory
spec:
  hosts:
  - {{ .Values.istio.istio_lb_host }}
  gateways:
  - {{ .Values.istio.istio_gateway }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ template "artifactory.nginx.fullname" . }}
        port:
          number: 80
{{- end }}